version: '3.8'

services:
  jupyter:
    build: .
    image: jupyter-js:latest
    ports:
      - "8887:8888"
    volumes:
      - .:/home/jovyan/work/
    command: start-notebook.sh --NotebookApp.token='' --notebook-dir=/home/jovyan/work/Appunti
